# Generated by Django 5.2.2 on 2025-06-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('HIIT', 'HIIT')], max_length=30)),
                ('instructor', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('total_slots', models.PositiveIntegerField()),
                ('available_slots', models.PositiveIntegerField()),
            ],
        ),
    ]
