# Generated by Django 5.2.2 on 2025-06-05 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fb_API.fitnessclass')),
            ],
        ),
    ]
